name: Test docker image creation
on:
  push:
    branches:
      - 'golang-1.15'
      - 'golang-1.16'
      - 'debian-buster'
      - 'terraform'
      - 'ruby-3.0'
jobs:
  push_to_registry:
    name: Build Docker image from Dockerfile
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: "0.14.7"
    steps:
      - name: Get Branch Name
        run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"
        id: get-branch-name
      - name: Show Branch Name
        run: echo ${{ steps.get-branch-name.outputs.BRANCH_NAME }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Testing Docker Build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ./devcontainer/${{ steps.get-branch-name.outputs.BRANCH_NAME }}/Dockerfile
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: ${{ secrets.DOCKERHUB_REPONAME }}/${{ steps.get-branch-name.outputs.BRANCH_NAME }}:test
