name: terraform-1.1 docker image creation
on:
  schedule:
    - cron: '0 19 * * *'
jobs:
  push_to_registry:
    name: Build Docker image from Dockerfile
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: "1.1.0"
    steps:
      - name: Get Branch Name
        run: echo "::set-output name=BRANCH_NAME::terraform-1.1"
        id: get-branch-name
      - name: Show Branch Name
        run: echo ${{ steps.get-branch-name.outputs.BRANCH_NAME }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./devcontainer/${{ steps.get-branch-name.outputs.BRANCH_NAME }}/Dockerfile
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_REPONAME }}/${{ steps.get-branch-name.outputs.BRANCH_NAME }}:latest
            ${{ secrets.DOCKERHUB_REPONAME }}/${{ steps.get-branch-name.outputs.BRANCH_NAME }}:${{ env.TERRAFORM_VERSION }}
